config/routes.rb
Rails.application.routes.draw do
  resources :transactionns

  resources :purchases

  resources :transactions

  get 'gallery/create'
  get 'gallery/update'

  mount Ckeditor::Engine => '/ckeditor'

  root to: 'visitors#index'

  get "contact" => "visitors#contact"
  get "blog" => "visitors#blog"
  get "order" => "visitors#order"
  get "checkout" => "visitors#checkout"

  get "admin" => "admin#index"
  get "articles" => "articles#index"


  post "visitors/receive" => "visitors#receive"
  post "transactionns/:id" => "transactionns#post"

  devise_for :users

  resources :users
  resources :designs
  resources :products
  resources :articles
  resources :contents
  resources :galleries
  resources :admin
  resources :charges
  resources :transactions
  resources :purchases
end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/content.rb
class Content < ActiveRecord::Base
  has_many :galleries, dependent: :destroy
end

app/models/design.rb
class Design < ActiveRecord::Base
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  belongs_to :contents
  has_attached_file :image
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/product.rb
class Product < ActiveRecord::Base

  has_attached_file :image
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
  belongs_to :transactionns

  def total
    self.price + self.shipping
  end
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  has_many :purchases
end

app/models/transactionn.rb
class Transactionn < ActiveRecord::Base
  has_many :purchases, dependent: :destroy
  attr_accessor :products, :stripe_card_token

  def full_shipping_address
    if shipping_address
      shipping_address + ', ' + shipping_city + ', ' + shipping_state + ', ' + shipping_zip.to_s
    else
      address + ', ' + city + ', ' + state + ', ' + zip.to_s
    end


  end



end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

	before_filter :redirect

	def redirect
		redirect_to '/users/sign_in/' unless current_user.try(:role) == "admin"
	end

	def index
 		@product = Product.new
		@products = Product.order(:order)
		@users = User.all
		@article = Article.new
		@articles = Article.order("created_at DESC")
		@design = Design.new
		@designs = Design.all
		@content = Content.new
		@content_items = Content.all
		@gallery = Gallery.new
		puts @post || "No"
		@transactions = Transactionn.all.order("id DESC")
	end



end

app/helpers/admin_helper.rb
module AdminHelper

  def catcount_to_cat(catcount)
    hash = { 1 => "About", 2 => "Advantages", 3 => "Tech Specs", 4 => "Usage", 5 => "FAQ" }
    hash[catcount]
  end

  def cat_to_active(catcount)
    if catcount == 1
      "active"
    end
  end

  def img_to_col_count(catcount)
    galcat = 12
    Content.where(:category => catcount).each do |x|
      if x.galleries.count != 0
        galcat = "6"
      end
    end
    galcat
  end

  def complete_to_color(complete)
    if complete == true
      "green"
    else
      "red"
    end
  end

  def complete_to_context(complete)
    if complete == true
      "Complete"
    else
      "Outstanding"
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/designs_helper.rb
module DesignsHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/admin/index.html.erb
<!--<h1>Admin Panel</h1>-->

<div id="linkbox" style="margin: 10px;">
    <% if user_signed_in? %>
        <%= link_to('Logout', destroy_user_session_path, :method => :delete) %> |
        <%= link_to('Edit Account', edit_user_registration_path) %>
    <% else %>
        <%= link_to('Login', new_user_session_path)  %> |
        <%= link_to('Register', new_user_registration_path)  %>
    <% end %>
</div>


<div class="container-push">

  <!-------->
  <div id="content">
    <ul id="tabs" class="nav nav-tabs" data-tabs="tabs">
      <li class="active"><a href="#Products" data-toggle="tab">Products</a></li>
      <li><a href="#Content" data-toggle="tab">Content</a></li>
      <li><a href="#Contact" data-toggle="tab">Contact</a></li>
      <li><a href="#Blog" data-toggle="tab">Blog</a></li>
      <li><a href="#Transactions" data-toggle="tab">Transactions</a></li>
      <li><a href="#Users" data-toggle="tab">Users</a></li>
    </ul>
    <div id="my-tab-content" class="tab-content">

      <!------------------------------------------------------ Product - START ----------------------------------------------------------------------->


      <div class="tab-pane active" id="Products">

        <h1 style="margin-left:30px;">Products</h1>
        <div class="well">
            <h3>Add Product: </h3>
            <%= bootstrap_form_for(@product, :html => {:multipart => true}, layout: :horizontal, control_col: "col-sm-4") do |f| %>
                <%= f.text_field :name %><br/>
                <%= f.text_area :description %><br/>
                <%= f.number_field :size, label: "Default # in bundle" %><br/>
                <%= f.number_field :stock %><br/>
                <%= f.number_field :serial %><br/>
                <%= f.number_field :price, label: "Price (In cents)" %><br/>
                <%= f.number_field :shipping, label: "Shipping Cost (In cents)" %><br/>
                <%= f.text_field :order %><br/>
                <%= f.file_field :image %><br/>
                <span style="margin-left:10vw"><%= f.submit %></span><br/><br/>
            <% end %>
        </div>

        <% @products.each do |g| %>
            <div class="well">
                <p>Name: <%= g.name %></p>
                <p>Description: <%= g.description.html_safe %></p>
                <p># in bundle: <%= g.size %></p>
                <p># in Stock: <%= g.stock %></p>
                <p>Serial #: <%= g.serial %></p>
                <p>Price: <%= number_to_currency(g.price/100.00) %></p>
                <p>shipping cost: <%= number_to_currency(g.shipping/100.00) %></p>
                <p>Position #: <%= g.order %></p>
                <%= image_tag g.image.url, :class => 'sized pull-left' %><br/>
                <div style="clear:both;">
                    <%= link_to "Delete", product_path(g), method: :delete %> |
                    <%= link_to "Edit", edit_product_path(g) %>
                </div>
                <br/>
            </div>
        <% end %>


      </div>
      <!------------------------------------------------------ Product - END ----------------------------------------------------------------------->
      <!------------------------------------------------------ Content - START ----------------------------------------------------------------------->
      <div class="tab-pane" id="Content">
        <h1 style="margin-left:30px;">Content</h1>

        <div class="well">
          <%= bootstrap_form_for @content, controller: :contents, action: :create, layout: :inline do |content| %>
              <h3>Add a new content block</h3><br/>
              <%= content.text_field :title %>
              <%= content.select :category, [["About", 1], ["Advantages", 2], ["Tech Specs", 3], ["Usage", 4], ["FAQ", 5]], {label: "Category"}, {class: "selectpicker"} %>
              <%= content.number_field :order, {label: "Position #"} %><br/><br/>
              <%= content.text_area :body, :rows => 5, :cols => 100 %><br/><br/>
              <%= content.primary "Add content block" %>
          <% end %>
        </div>




        <% 5.times do |catcounter| %>
            <% catcount = catcounter + 1 %>
            <div class="well">
              <h3><%= catcount_to_cat(catcount) %></h3>
              <% @content_items.where(:category => catcount.to_s).order(:order).each do |f| %>
                  <div class="well">
                    <div class="row">
                      <div class="col-md-6">
                        <h3><%= f.order.ordinalize %> content block</h3>
                        <h5><%= f.title %></h5>
                        <%= f.body.html_safe %><br/>
                        <%= link_to "Delete", content_path(f), method: :delete, data: {confirm: "Are you sure you wish to delete this content block? It can not be restored."} %>
                        |
                        <%= link_to "Edit", edit_content_path(f) %>
                      </div>
                      <div class="col-md-6">
                        <h3>Add New Image</h3>

                        <%= bootstrap_form_for(@gallery, :html => {:multipart => true}, layout: :inline, action: :create) do |g| %>
                            <%= g.number_field :order %>
                            <%= g.number_field :width %><br/>
                            <%= g.hidden_field :content_id, value: f.id %><br/>
                            <%= g.file_field :image %><br/><br/>
                            <%= g.primary "Add image" %>
                        <% end %>
                      </div>
                    </div>
                    <div class="image_box">
                      <h3>Images:</h3>


                      <% Gallery.where(:content_id => f).order(:order).each do |h| %>
                          <div class="image_box_inner">
                            <p>Image <%= h.order %> | Width: <%= h.width %>px</p>
                            <%= link_to "Delete", gallery_path(h), method: :delete, data: {confirm: "Are you sure you wish to delete this image? It can not be restored."} %>
                            <%= image_tag h.image.url, :style => "height: 200px; margin-left:0px;" %>
                          </div>
                      <% end %>
                      <div style="clear:both;"></div>
                    </div>
                  </div>


              <% end %>


            </div>
        <% end %>


      </div>
      <!------------------------------------------------------ Content - END ----------------------------------------------------------------------->
      <!------------------------------------------------------ Contact - START ----------------------------------------------------------------------->
      <div class="tab-pane" id="Contact">
        <h1 style="margin-left:30px;">Contact Info</h1>


        <div class="well">
          <h4>New contact</h4>

          <%= bootstrap_form_for @design, layout: :horizontal, control_col: "col-sm-6" do |i| %>
              <%#= i.text_field :sitename %>
              <%= i.text_field :name %>
              <%= i.text_field :email %>
              <%= i.text_field :phone %>
              <%= i.text_field :address %>
              <span style="margin-left:10vw"><%= i.submit "New Contact Block" %></span>
          <% end %>

        </div>



        <% @designs.each do |f| %>
            <div class="well">
              <h3><%= f.name %></h3>
              <p><%= number_to_phone(f.phone) %></p>
              <p><%= f.email %></p>
              <p><%= f.address.html_safe %></p>
              <%= link_to "Edit Article", edit_design_path(f) %> |
              <%= link_to "Delete", design_path(f), method: :delete, data: {confirm: "Are you sure you wish to delete this contact? It can not be restored."} %>
            </div>
        <% end %>















      </div>

      <!------------------------------------------------------ Contact - END ----------------------------------------------------------------------->
      <!------------------------------------------------------ Blog - START ----------------------------------------------------------------------->
      <div class="tab-pane" id="Blog">
        <h1 style="margin-left:30px;">Blog</h1>

        <div class="well">
          <h4>New post</h4>
          <%= bootstrap_form_for @article do |f| %>
              <%= f.text_field :title %>
              <%= f.label :body %>
              <%= f.cktext_area :body, rows: 10 %><br/>
              <%= f.submit %>
          <% end %>
        </div>


        <% @articles.each do |article| %>
            <div class="well">
              <h3><%= article.title.html_safe %></h3>
              <h4><%= article.created_at.strftime("%Y-%m-%d") %></h4>
              <p><%= article.body.html_safe %></p>
              <%= link_to "Edit Article", edit_article_path(article) %> |
              <%= link_to "Delete", article_path(article), method: :delete, data: {confirm: "Are you sure you wish to delete this article? It can not be restored."} %>
            </div>
        <% end %>

        <br/>


      </div>
      <!------------------------------------------------------ Blog - END ----------------------------------------------------------------------->
      <!------------------------------------------------------ Transactions - START ----------------------------------------------------------------------->
      <div class="tab-pane" id="Transactions">

        <h1 style="margin-left:30px;">Orders</h1>
        <div class="container">







        <% @transactions.each do |f| %>
            <div class="well">
              <div class="panel-body">
                <div class="col-md-6">
                  <p><b>Name: </b><%= f.first_name || "N/A" %></p>
                  <p><b>Address: </b><%= f.full_shipping_address %></p>
                  <p><b>Telephone Number: </b> <%= number_to_phone(f.phone) || "N/A" %></p>
                  <p><b>Email: </b><%= f.email || "N/A" %></p>
                </div>
                <div class="col-md-6">
                  <p><b>Status: </b><span style=" margin-right:30px; color:<%= complete_to_color(f.complete) %>;"><%= complete_to_context(f.complete) %></span> <%= link_to 'Mark as completed', transactionn_path(f), method: :post unless f.complete == true %> </p>
                  <p><b>Date: </b><%= f.created_at.strftime("%Y-%m-%d") %></p>
                  <p><b>Order size: </b><%= f.purchases.count %></p>
                  <p><b>Total: </b><%= number_to_currency((f.purchases.sum(:price) + f.purchases.sum(:shipping))/100.00) %></p>
                  <%= link_to "Remove order", transactionn_path(f), method: :delete, data: {confirm: "Are you sure you wish to delete this order? It can not be restored."} %>

                </div>

              </div>

              <table class="table">
                <% f.purchases.each do |g| %>
                    <tr>
                      <td style="width:500px;"><%= g.name %></td>
                      <td style="width:500px;">#<%= g.serial %></td>
                      <td style="width:500px;"><%= number_to_currency(g.price/100) %> + <%= number_to_currency(g.shipping/100) %> (Shipping)</td>
                    </tr>
                <% end %>
              </table>
            </div><!--well-->
        <%end%>

        </div>


      </div>
      <!------------------------------------------------------ Transactions - END ----------------------------------------------------------------------->
      <!------------------------------------------------------ Users - START ----------------------------------------------------------------------->
      <div class="tab-pane" id="Users" style="margin-bottom: 550px;">

        <h1 style="margin-left:30px;">Users</h1>
        <div class="container">
        <div class="panel panel-default">

          <div class="panel-heading">Manage Users</div>
          <div class="panel-body">
            Only Admins can sign onto the admin panel.<br />
            To share admin functionality with others, simply change their role from 'User' to 'Admin'.<br />
            Note: VIPs, like Users, have no ability to view or edit content in the admin panel.
          </div>

          <table class="table">
            <tbody>
            <% @users.each do |user| %>
                <tr>
                  <%= render user %>
                </tr>
            <% end %>
            </tbody>
          </table>
        </div>
        </div>
      </div>
      <!------------------------------------------------------ Users - END ----------------------------------------------------------------------->
    </div>
  </div>







  <script type="text/javascript">
      jQuery(document).ready(function ($) {
          $('#tabs').tab();
      });
  </script>

</div> <!-- container -->

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
    <li><%= link_to 'Sign in', new_user_session_path %></li>
    <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
    <li><%= link_to 'Sign in', new_user_session_path %></li>
    <li><%= link_to 'Sign up', new_user_registration_path %></li>
    <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% end %>
<% if user_signed_in? %>
    <% if current_user.admin? %>
        <li><%#= link_to 'Admin', '/admin' %></li>
        <li><a>Content</a></li>
        <li><a>Products</a></li>
        <li><a>Contact Info</a></li>
        <li><%= link_to 'Approve users', users_path %></li>
        <li><%= link_to 'Edit account', edit_user_registration_path %></li>
        <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
    <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flat-Jack</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://js.stripe.com/v2/", "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= tag :meta, name: 'stripe-key', content: ENV['STRIPE_TEST_PUBLISHABLE_KEY'] %>

  <link rel="shortcut icon" href="img/favicon.ico" type="image/x-icon; charset=binary">
  <%#= favicon_link_tag'/myicon.ico' %>
  <link rel="stylesheet" href="css/cosmos.css" />
  <link rel="stylesheet" type="text/css" href="css/styles.css" />



</head>
<body>
<nav class="navbar navbar-default">

  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->

    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" style="visibility: hidden;" data-toggle="collapse" data-target="#droparea">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!--<a class="navbar-brand" href="index.html"><img height=25px src="logo.png"/></a>-->
      <%#= image_tag 'logo.png' %>
      <!--<a href="/"><%#= image_tag 'logo.png', :class => "top-icon navbar-brand" %></a>-->
      <img href="/" alt="Logo" class="top-icon navbar-brand" src="/assets/logo-d4bf43ff9880030c57ab34ae1a60db07.png">
    </div>
    <!--<div>-->
      <!--Made and Engineered in Germany-->
      <!--Simply on Air-->
    <!--</div>-->

    <ul class="nav navbar-nav navbar-left">
      <li class="h4" style="padding-top: 5px;">Made and Engineered in Germany - Simply on Air</li>
    </ul>

    <!--<div class="navbar-header">-->
        <!--&lt;!&ndash;<h4 style="margin-top: 15px;">Made and Engineered in Germany <span class="h4">- simply on air</span></h4>&ndash;&gt;-->
    <!--</div>-->
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="droparea">

      <ul class="nav navbar-nav navbar-right">
        <li><a href="/"><b>Home</b></a></li>
        <li><a href="blog"><b>Blog</b></a></li>
        <!--<li><a href="press.html"><b>Press</b></a></li>-->
        <li><a href="contact"><b>Contact</b></a></li>
        <li><a href="order"><b>Order</b></a></li>
        <% if user_signed_in? %>
            <li><a href="/admin"><b>Admin</b></a></li>
        <% end %>
        <!--<li><a href="cart.html"><b>Cart</b></a></li>-->
      </ul>
    </div>
    <!-- /.navbar-collapse -->

  </div>
  <!-- /.container-fluid -->

</nav>

<%= render partial: '/layouts/messages' %>

<div class="myborder"></div>
    <%= yield %>
<div class="myborder"></div>

<div class="myfooter">
  <div class="row">
    <div class="col-md-2"><%= image_tag 'logo.png', :class => "bottom-icon" %></div>
    <% if Design.count > 0 %>
        <% @designs = Design.first %>
    <div class="col-md-2"><%= @designs.email %></div>
    <div class="col-md-1"><%= number_to_phone(@designs.phone, area_code: true) %></div>
    <% end %>
    <div class="col-md-3"></div>
    <div class="col-md-3">
      <div class="copyright">&copy; 2014 flat-jack<sup>&#174;</sup></div>
    </div>
    <div class="col-md-1">
      <div id="fb-root"></div>
      <div class="fb-like" data-href="https://www.facebook.com/pages/Flat-Jack/774414999312633" data-width="120" data-layout="button" data-action="like" data-show-faces="false" data-share="true"></div>
    </div>
  </div>
</div>



</body>








<script>
    (function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.0";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));

    if($('.navbar-toggle').css('display') !='none'){
        $(".navbar-toggle").trigger( "click" );
    }

    $( document ).ready(function() {
        $('.navbar-toggle').click();
    });
</script>







<script>
    $('.titletext').prepend('<img src="img/yellowlines.png" style="height:15px; width:30px; margin-right:5px; padding-top:5px; float:left;" />');
</script>

</html>